config/routes.rb
Rails.application.routes.draw do

  get 'chatrooms/show'

  get "/chat", to: "chatrooms#show"


  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  devise_for :users
scope path: "/chefs", controller: :users do
 get '/' => :index, as: 'chefs'
  get "/:id" => :show, as: "chef"
  get "/:id/edit" => :edit, as: "edit_chef"
  patch "/:id" => :update, as: "patch_chef"
  delete "/:id" => :destroy, as: "destroy_chef"
end
  resources :messages, :only => [:create]
  resources :ingredients
  resources :recipes do
    resources :comments, :only =>  [:create]
    member do
      post 'like'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, :through => :recipe_ingredients
  has_many :comments, :dependent => :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :image, ImageUploader


  validates_presence_of :name, :description, :user
  validates_length_of :description, minimum: 5 ,maximum: 500
  default_scope -> {order(updated_at: :desc)}


  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_user_for_like, :only => [:like]
  before_action :authenticate_user!, :only => [:new, :edit, :destroy]
  prepend_before_action  :set_recipe, only:  [:show, :edit, :update, :destroy, :like]

  before_filter :check_chef, only: [:edit, :destroy]
  def index
    @recipes = Recipe.paginate(:page => params[:page], per_page: 5)
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(:page => params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new

  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe, notice: 'The recepy was successfully created'
    else
      render :new
    end
  end


  def edit

  end

  def update
    @recipe.update_attributes(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "The recipe was updated"
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path, notice: "#{@recipe.name} was successfully deleted"
    end
  end

  def like
    like = Like.create(like: params[:like], user: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was succesful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  private
  def require_user_for_like
    unless user_signed_in?
      redirect_to :back, :alert => "You must be logged in to perform that action"

    end
  end

  def check_chef
    unless @recipe.user == current_user || current_user.admin?
      redirect_to recipes_path, notice: "You must be an owner"
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :image,ingredient_ids: [])
  end

  def set_recipe
    @recipe =Recipe.find(params[:id])
  end
end

app/views/recipes/_form.html.slim
= render 'shared/errors', item: @recipe



.row
  .col-md-12
    = form_for(@recipe,html: { class: 'form-horizontal', role: 'form', :multipart => true }) do |f|
      .form-group
        .control-label.col-md-2
          = f.label :name

        .col-md-8
          = f.text_field :name, class: 'form-control' , :placeholder => "Name of recipe",  :autofocus => true

      .form-group
        .control-label.col-md-2
          = f.label :description

        .col-md-8
          = f.text_area :description,rows: 10, class: 'form-control', :placeholder => "Enter steps to create recipe"

        .row
          .col-md-offset-2.col-md-8
            = f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cc|
              - cc.label(class: "checkbox-inline input-checkbox") {cc.check_box(class: "checkbox") + cc.text}

      .form-group
        .control-label.col-md-2
          = f.label :image, "Add Image"

        .col-md-8
          = f.file_field :image, accept: "image/jpeg,image/gif,image/png"

      .form-group
        .col-md-offset-2.col-md-10
          = f.submit class: "btn btn-primary btn-lg btn-xlarge"

  .col-md-offset-4.col-md-4
    | [
    = link_to "Cancel request and return to recipes listing", recipes_path, class: "color-match"
    | ]

app/views/recipes/_recipe.html.slim
- obj.each do |receipe|
  .row

    .col-md-2
      section.center.user_info
        = gravar_for(receipe.user, size: 120)


    .col-md-8.well
      .col-md-2.pull-left
        = image_tag(receipe.image.url, size: "150x100", class: "img-circled spiffy-image img-responsive") if receipe.image?
      col-md-8
        .center
          h4= link_to receipe.name, recipe_path(receipe)
          p= truncate  receipe.description, length: 150
          - if receipe.ingredients.any?
            p
              | Ingredients:
              = render receipe.ingredients

          p
            span.quiet
              small
                = "Created at".concat(" ") + time_ago_in_words(receipe.created_at).concat(" by ") \
                 +receipe.user.name.capitalize  + " | "  + pluralize(receipe.comments.count, "Comment")


        .recipe-actions
          - if user_signed_in? && ( receipe.user == current_user || current_user.admin?)

            = link_to "Edit recipe", edit_recipe_path(receipe), class: "btn btn-xs btn-warning"
            = link_to "Delete recipe", recipe_path(receipe), method: :delete, data: {confirm: " Are you sure?"}, class: "btn btn-xs btn-danger"


      .row
        .pull-right.liking
          = link_to like_recipe_path(receipe, like: true), method: :post do
            i.glyphicon.glyphicon-thumbs-up
            = " "
            = receipe.thumbs_up_total
          =   " || "
          =  link_to like_recipe_path(receipe, like: false), method: :post do
            i.glyphicon.glyphicon-thumbs-down
            = " "
            = receipe.thumbs_down_total

app/views/recipes/edit.html.slim
= render 'shared/page_title', title: "Edit the recipe"

= render  'form'

app/views/recipes/index.html.slim
= render 'shared/page_title', title: "showing all recipes"
.center
  = will_paginate renderer: BootstrapPagination::Rails

= render 'recipes/recipe', obj: @recipes

.center
  = will_paginate renderer: BootstrapPagination::Rails

app/views/recipes/new.html.slim
= render 'shared/page_title', title: "Create a neew recipe"

= render  'form'

app/views/recipes/show.html.slim
= render 'shared/page_title', title: @recipe.name
.col-md-offset-2.col-md-8.well
  .center
    = image_tag @recipe.image_url if @recipe.image?
  h4.center.description
    strong Description:
  hr

  = simple_format @recipe.description
  hr
  - if @recipe.ingredients.any?
    p
      | Ingredients:
      = render @recipe.ingredients

  .pull-right
    p.center
      em Created by:

    p.center= link_to gravar_for(@recipe.user), chef_path(@recipe.user)

    p.center
      small= @recipe.user.name.capitalize

      .pull-right= "created: " + time_ago_in_words(@recipe.created_at).concat(" ago")


  .recipe-actions
    -  if user_signed_in? && (@recipe.user == current_user || current_user.admin?)
      = link_to "Edit recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning"
      = link_to "Delete recipe", recipe_path(@recipe), method: :delete, data: {confirm: " Are you sure?"}, class: "btn btn-xs btn-danger"
    = link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary"

  .row.center
    .row.col-md-7.col-md-offset-7
      = link_to like_recipe_path(@recipe, like: true), method: :post do
        i.glyphicon.glyphicon-thumbs-up
      = @recipe.thumbs_up_total
      = " || "
      = link_to like_recipe_path(@recipe, like: false), method: :post do
        i.glyphicon.glyphicon-thumbs-down
      = @recipe.thumbs_down_total
- if user_signed_in?
  .row
    .col-md-8.col-md-offset-2
      h3 Comments
      hr
      = form_for([@recipe, @comment],remote: true, html: {class: 'form-horizontal', role: 'form'}) do |f|
        .form-group
          .control-label.col-md-2
            = f.label :description, "Comment"

          .col-md-8
            = f.text_area :description, rows: 8, class: 'form-control', :placeholder => "Enter comment here"

        .form-group
          .col-md-offset-2.col-md-10
            = f.submit "Submit Comment",class: "btn btn-primary btn-lg btn-xlarge"

      hr

.row
  .col-md-8.col-md-offset-2
    - if @recipe.comments.any?
      h3 Prior Comments:
      #messages
        = render partial: 'comments/comments', object: @comments
    - else
      h3 No comments yet :(