config/routes.rb
Rails.application.routes.draw do

  get 'chatrooms/show'

  get "/chat", to: "chatrooms#show"


  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  devise_for :users
scope path: "/chefs", controller: :users do
 get '/' => :index, as: 'chefs'
  get "/:id" => :show, as: "chef"
  get "/:id/edit" => :edit, as: "edit_chef"
  patch "/:id" => :update, as: "patch_chef"
  delete "/:id" => :destroy, as: "destroy_chef"
end
  resources :messages, :only => [:create]
  resources :ingredients
  resources :recipes do
    resources :comments, :only =>  [:create]
    member do
      post 'like'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, :through =>  :recipe_ingredients
  validates :name, presence: true, length:  {:minimum => 3, :maximum => 25 }
  validates_uniqueness_of :name
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :require_admin, except:  [:show, :index]
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)

  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient, notice: "You hav successfully created ingredient"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @ingredient.update_attributes(ingredient_params)

  if @ingredient.save
    redirect_to @ingredient, notice: 'You have successfully updated  ingredient'
  else
    render 'edit'
  end
  end

  def destroy
  end

  private
  def require_admin
     unless user_signed_in? && current_user.admin?
       redirect_to ingredients_path, alert: "only  admin users can perform this action"
     end
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/ingredient_helper.rb
module IngredientHelper
  def is_new_ingredient?(ingredient)
    if ingredient.new_record?
      "Add ingredient"
    else
      "Update ingredient"
    end
  end
end

app/views/ingredients/_form.html.slim
= render 'shared/errors', item: @ingredient
row
  .col-md-12
    = form_for(@ingredient,html: { class: 'form-horizontal', role: 'form' }) do |f|
      .form-group
        .control-label.col-md-2
          = f.label :name

        .col-md-8
          = f.text_field :name, class: 'form-control' , :placeholder => "Enter ingredient",  :autofocus => true



      .form-group
        .col-md-offset-2.col-md-10
          = f.submit is_new_ingredient?(@ingredient),class: "btn btn-primary btn-lg btn-xlarge"

  .col-md-offset-4.col-md-4
    | [
    = link_to "Cancel request and return to recipes listing", recipes_path, class: "color-match"
    | ]

app/views/ingredients/_ingredient.html.slim
span.badge
  = link_to ingredient.name, ingredient
  | &nbsp;

app/views/ingredients/edit.html.slim
= render 'shared/page_title', title: "Edit Ingredient name"
= render 'form'

app/views/ingredients/index.html.slim
= render 'shared/page_title', title: "Available ingredients"
.center
  = will_paginate renderer: BootstrapPagination::Rails
.center
  - @ingredients.each do |ingr|
    ul.listing
      .row
        .well.col-md-offset-4.col-md-4
          li.chef-title= link_to ingr.name.capitalize, ingredient_path(ingr)
          li
            small= pluralize(ingr.recipes.count, "recipe") if ingr.recipes
          - if user_signed_in? && current_user.admin?
            li= link_to "Edit this ingredient", edit_ingredient_path(ingr)
.center
  = will_paginate renderer: BootstrapPagination::Rails

app/views/ingredients/new.html.slim
= render 'shared/page_title', title: "Create New Ingredient"
= render 'form'

app/views/ingredients/show.html.slim
= render'shared/page_title', title: " #{@ingredient.name}"

- if @ingredient.recipes.any?
  h4 align="center" Recipe' containin #{@ingredient.name}
  div align="center"
  = will_paginate @ingredient_recipes, renderer: BootstrapPagination::Rails
  = render 'recipes/recipe', obj: @ingredient_recipes
  = will_paginate @ingredient_recipes, renderer: BootstrapPagination::Rails

- else
    h4 align="center" No Recipes yet :(