config/routes.rb
Rails.application.routes.draw do

  get 'chatrooms/show'

  get "/chat", to: "chatrooms#show"


  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  devise_for :users
scope path: "/chefs", controller: :users do
 get '/' => :index, as: 'chefs'
  get "/:id" => :show, as: "chef"
  get "/:id/edit" => :edit, as: "edit_chef"
  patch "/:id" => :update, as: "patch_chef"
  delete "/:id" => :destroy, as: "destroy_chef"
end
  resources :messages, :only => [:create]
  resources :ingredients
  resources :recipes do
    resources :comments, :only =>  [:create]
    member do
      post 'like'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: {
      :minimum => 4, :maximum => 140
  }
  belongs_to :user
  belongs_to :recipe
  validates_presence_of :user, :recipe

default_scope -> {order(:updated_at => :desc)}
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name,  :email, :id

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, :through =>  :recipe_ingredients
  validates :name, presence: true, length:  {:minimum => 3, :maximum => 25 }
  validates_uniqueness_of :name
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates_uniqueness_of :user_id, scope: :recipe

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates_presence_of :content, :user

  scope :most_recent, -> { order(:created_at).last(20)}

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, :through => :recipe_ingredients
  has_many :comments, :dependent => :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :image, ImageUploader


  validates_presence_of :name, :description, :user
  validates_length_of :description, minimum: 5 ,maximum: 500
  default_scope -> {order(updated_at: :desc)}


  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
belongs_to :ingredient
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy


  validates_presence_of :name
  validates_length_of :name, maximum: 30
  validates_length_of :email, maximum: 255
  validates_uniqueness_of :email
  validates_presence_of :email, case_sensitive: false
  VALID_EMAILS_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_format_of :email, with: VALID_EMAILS_REGEX
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create

    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
    else
      redirect_to :back, alert: "Comment was not created"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if user_signed_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_user_for_like, :only => [:like]
  before_action :authenticate_user!, :only => [:new, :edit, :destroy]
  prepend_before_action  :set_recipe, only:  [:show, :edit, :update, :destroy, :like]

  before_filter :check_chef, only: [:edit, :destroy]
  def index
    @recipes = Recipe.paginate(:page => params[:page], per_page: 5)
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(:page => params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new

  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe, notice: 'The recepy was successfully created'
    else
      render :new
    end
  end


  def edit

  end

  def update
    @recipe.update_attributes(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "The recipe was updated"
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path, notice: "#{@recipe.name} was successfully deleted"
    end
  end

  def like
    like = Like.create(like: params[:like], user: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was succesful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  private
  def require_user_for_like
    unless user_signed_in?
      redirect_to :back, :alert => "You must be logged in to perform that action"

    end
  end

  def check_chef
    unless @recipe.user == current_user || current_user.admin?
      redirect_to recipes_path, notice: "You must be an owner"
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :image,ingredient_ids: [])
  end

  def set_recipe
    @recipe =Recipe.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  prepend_before_action :set_user, only: [:show,  :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit]
  before_action :require_same_chef, only: [:edit]


  def index
    @users =User.paginate(page: params[:page], per_page: 5)


  end

  def show
    @chef_recipes = @user.recipes.paginate(page: params[:page], per_page: 5)


  end

  def edit

  end

  def update
    if @user.update(chefs_params)
      redirect_to chef_path(@user),  notice: "You have successfully edited your profile"
    else
      render 'edit'

    end
  end

  def destroy
    unless @user.admin?
      if @user.destroy
        redirect_to chefs_path, notice: "#{@user.name} has canceled his account"
      else
        render 'show'
      end
    else
      redirect_to chefs_path
    end

  end


  private

  def set_user
    @user = User.find(params[:id])

  end
  def require_admin
    unless current_user.admin?
      redirect_to chef_path(current_user), alert: "This action can be performed only by admin"
    end
  end

  def require_same_chef
    unless @user == current_user || current_user.admin?
      # flash[:alert] ="You must be the owner of the account to perform edit and delte actions"
      redirect_to chefs_path , alert: "You must be the owner of the account to perform edit and delte actions"

    end
  end

  def chefs_params
    params.require(:user).permit(:name,:email, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end

end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
  def is_new_ingredient?(ingredient)
    if ingredient.new_record?
      "Add ingredient"
    else
      "Update ingredient"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recepies_helper.rb
module RecepiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'My Recepies', root_path, class: 'navbar-brand', id: 'logo'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav

        li
          = link_to "Chefs", chefs_path
        li
          = link_to "View all recipes", recipes_path

        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Ingredients
            span.caret
          ul.dropdown-menu
            li
              =link_to "All Ingredients", ingredients_path

            -  Ingredient.all.each do |ingredient|
              li= link_to ingredient.name, ingredient


            - if user_signed_in? && current_user.admin?
              li
                a href="#"  Separated link
              li
                = link_to "Create a new ingredient", new_ingredient_path

        - if current_user
          li
            = link_to "Chef Chat", chat_path
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              | Recipes
              span.caret
            ul.dropdown-menu
              li
                = link_to "Create a new recipe", new_recipe_path
              li
                a href="#"  Another action
              li
                a href="#"  Something else here
              li.divider role="separator"
              li
                a href="#"  Separated link
              li.divider role="separator"
              li
                a href="#"  One more separated link


      form.navbar-form.navbar-left
        .form-group
          input.form-control placeholder="Search" type="text" /
        button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        - unless !current_user
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              = current_user.name.capitalize.concat("'s profile")
              span.caret
            ul.dropdown-menu
              li= link_to "View your profile", chef_path(current_user)

              li= link_to "Edit your profile", edit_chef_path(current_user)

              li
                a href="#"  Something else here
              li.divider role="separator"
              li= link_to "log out", destroy_user_session_path, method:  :delete

        -else
          li= link_to "Log in", new_user_session_path
          li= link_to "Registration", new_user_registration_path

app/views/layouts/_not_footer.html.slim
link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" /
footer
  #footer.footer
    .container
      .row
        .col-lg-2.col-md-2.col-sm-4.col-xs-6
          h3 Links
          ul
            li= link_to 'About', '#'

            li= link_to "Recipes", recipes_path

            li= link_to 'Chefs', chefs_path

            li= link_to 'Ingredients', ingredients_path

        .col-lg-2.col-md-2.col-sm-4.col-xs-6
          h3 Numbres
          ul
            li
              a href="#"  One
            li
              a href="#"  Two
            li
              a href="#"  Three
            li
              a href="#"  Four
        .col-lg-2.col-md-2.col-sm-4.col-xs-6
          h3 Strings
          ul
            li
              a href="#"  String 1
            li
              a href="#"  String 2
            li
              a href="#" String 3
            li
              a href="#"  String 4
        .col-lg-2.col-md-2.col-sm-4.col-xs-6
          h3 Countries
          ul
            li
              a href="#"  USA
            li
              a href="#"  Sweden
            li
              a href="#"  Nederladns
            li
              a href="#"  Russia
        .col-lg-3.col-md-3.col-sm-6.col-xs-12
          h3 Send email here
          ul
            li
              .input-append.newsletter-box.text-center
                input.full.text-center placeholder=("Email ") type="text" /
                button.btn.bg-gray type="button"
                  | Lorem ipsum
                  i.fa.fa-long-arrow-right
          ul.social
            li
              a href="#"
                i.fa.fa-facebook  
            li
              a href="#"
                i.fa.fa-twitter  
            li
              a href="#"
                i.fa.fa-google-plus  
            li
              a href="#"
                i.fa.fa-pinterest  
            li
              a href="#"
                i.fa.fa-youtube  

  .footer-bottom
    .container
      p.pull-left My spiffy footer.
      .pull-right
        ul.nav.nav-pills.payments
          li
            i.fa.fa-cc-visa
          li
            i.fa.fa-cc-mastercard
          li
            i.fa.fa-cc-amex
          li
            i.fa.fa-cc-paypal

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    title PRORails5
    = viewport_meta_tag(:maximum_scale => "1.0")
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'


  body
    = render 'layouts/navigation'
    = bootstrap_flash
    div class="container"
      == yield

    == render 'layouts/not_footer'

app/views/pages/home.html.slim
div class='jumbotron center'
  h1
    | Welcome To My RECEPIES
  h2
    | The best recipes sharing app
  p= link_to 'View all recipes', recipes_path, class: 'btn btn-danger btn-lg btn-xlarge'

div class="row"
  div class="col-lg-4"
    h2 Heading
    p
      | Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    p
      a[ class="btn btn-primary btn-xlarge" href="#" role="button"] View details

  div class="col-lg-4"
    h2 Heading
    p
      | Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    p
      a[ class="btn btn-primary btn-xlarge" href="#" role="button"] View details

  div class="col-lg-4"
    h2 Heading
    p
      | Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
    p
      a( class="btn btn-primary btn-xlarge" href="#" role="button") View details

app/views/shared/_errors.html.slim
- if item.errors.any?
  .row
    .col-md-offset-2.col-md-8
      .panel.panel-danger
        .panel-heading
          h2.panel-title= pluralize(item.errors.count, "error") + " prohibited this #{item.class} from being saved:"

          .panel-body
            ul
              - item.errors.full_messages.each do |msg|
                li= msg

app/views/shared/_page_title.html.slim
h1.center= title.capitalize
hr